### ISSUE TITLE
using executequery with generated wsdl file

### ISSUE THREAD

**Issue by Randle-Lanre** [CiscoDevNet/axl-dotnet-samples#1]
I have been trying to use the executequery with the getphone and enduser,

all it returns is a system.object type,  how do i return data with the cucm axl api

**Comment by dstaudt** [comment]
Thanks for the question...

Added an executeSqlQuery.cs sample in this release https://github.com/CiscoDevNet/axl-dotnet-samples/releases/tag/v0.1
